version: 0.1

phases:
  pre_build:
    commands:
      - pip install cfn-response -t ./pip
  post_build:
    commands:
      - echo Build completed
artifacts:
   files: 
    - '**/*'
   base-directory: 'src'